### ISSUE TITLE
add too much space after word select item.

### ISSUE THREAD

**Issue by lethevinh** [marcusgreen/moodle-qtype_wordselect#10]
when displaying the question content , I found too much white space added before each word bolded or underlined.
![screenshot from 2018-03-23 16-17-39](https://user-images.githubusercontent.com/6895930/37821628-bbcaefe2-2eb6-11e8-921e-8c5c1e309b7e.png)

https://github.com/marcusgreen/moodle-qtype_wordselect/blob/8f91e7acaafd8efc213fa2d351ece14ffaa011cb/question.php#L575

**Comment by marcusgreen** [comment]
Which branch is that from. I have been working on a significant refactor in the main branch recently. It is not finished and I am aware of at least one fairly significant bug in it, but it is the general direction I am going in. The bug is that it does not handle selectables without spaces, i.e. it would render [cat]x[mat] incorrectly. I have been working on a fix for that but I will not have anything to show for at least a week or possibly more. When I do a new release I would like to give you credit for feedback, so send an email to marcusavgreen at gmail dot com if you would like me to include your details.

**Comment by marcusgreen** [comment]
Let me know if you are awesome with regular expressions as you might be able to fix that bug I just mentioned :)

**Comment by marcusgreen** [comment]
Closing this as lethevinh  is awesome with regular expressions....
