### ISSUE TITLE
Multiple questions with question type - qtype_wordselect not working

### ISSUE THREAD

**Issue by hdagheda** [marcusgreen/moodle-qtype_wordselect#29]
Thank you @marcusgreen for such great plugin, However I am unable to add multiple questions of qtype_wordselect on same page. when I click on word, its not getting selected. Its works when I have only one question of qtype_wordselect on page.

Please let me know will there be any future updates to fix this issue?
Thank you

**Comment by hdagheda** [comment]
In version 2.42 moodle version 3.4.9

**Comment by marcusgreen** [comment]
Hi, this issue was fixed in the last release
https://github.com/marcusgreen/moodle-qtype_wordselect/releases
But unfortunately the fix only works in Moodle 3.7 and above. You may find the question works correctly where you have an odd number of the questions on a single page. That is not a good solution I know. My apologies but I am not able to apply the fix for earlier versions of Moodle.

**Comment by hdagheda** [comment]
Thank you @marcusgreen , I understand.

**Comment by hdagheda** [comment]
adding below code in renderer.php has solved the issue.
```
// Initialize JS only once per page.
        static $jsinit = false;
        if (!$jsinit) {
            $this->page->requires->js_call_amd('qtype_wordselect/navigation', 'init');
            $this->page->requires->js_call_amd('qtype_wordselect/selection', 'init');
            $jsinit = true;
        }
```
