### ISSUE TITLE
Error during backup: Field "question" does not exist in table "question_wordselect"

### ISSUE THREAD

**Issue by leac** [marcusgreen/moodle-qtype_wordselect#7]
We tried to back up a course having this type of questions, and got the following error:
Field "question" does not exist in table "question_wordselect"

Here is a screenshot of the call stack:

![wordselect_error](https://cloud.githubusercontent.com/assets/1826720/20176794/162966f0-a752-11e6-99dc-ae3a0773bbeb.jpg)

What could be causing this?

**Comment by marcusgreen** [comment]
Just to acknowledge I have received your message and am investigating. In the mean time could you export an example of a wordselect question on your system in xml format and send it to marcusavgreen at gmail dot com.

**Comment by marcusgreen** [comment]
The backup/restore functionality was tested before it was submitted to the plugins database and I have just tested it successfully. Are you running the code from Github rather than the plugins database?.  I made a change to the code on August 28th just before my first release to the plugins database that may trigger this error. If you install the latest version I think this problem will go away.  

If you are interested in the details behind this you can see where I changed the code here.
https://github.com/marcusgreen/moodle-qtype_wordselect/commit/85f12db338b52a0991cb44407e93faa978f3186f

Please let me know if that addresses the issue.

**Comment by leac** [comment]
Thank you for your quick reply. 
I was running the code from the plugins database. So now I copied the changed code from the commit you mentioned, and that solved the problem. Thanks!
